PortafolioMALH2/Models/DesarrolladorModel.cs
using System.ComponentModel.DataAnnotations;

namespace PortafolioMALH2.Models
{
    public class DesarrolladorModel
    {
        [Key]
        public int Id { get; set; }

        [StringLength(60)]
        public string? NombreCompleto { get; set; }

        [DataType(DataType.Date)]
        public DateTime FechaNacimineto { get; set; }

        [RegularExpression(@"^\d+$", ErrorMessage = "Solo se permiten números.")]
        [StringLength(10)]
        public string? NumCel { get; set; }

        [StringLength(30)]
        public string? CorreoElec { get; set; }
        public string? ImagenURL { get; set; }
        public string? Descripcion { get; set; }
    }
}

PortafolioMALH2/Models/ErrorViewModel.cs
namespace PortafolioMALH2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PortafolioMALH2/Models/ProyectoTecs.cs
namespace PortafolioMALH2.Models
{
    public class ProyectoTecs
    {
        public string? NombreProyecto { get; set; }
        public string? descripcion { get; set; }
        public string? NombreTecnologia { get; set; }
        public string? Version_tec { get; set; }
        public int porcentaje { get; set; }
    }
}

PortafolioMALH2/Controllers/DesarrolladorController.cs
using Microsoft.AspNetCore.Mvc;
using PortafolioMALH2.Datos;
using PortafolioMALH2.Models;

namespace PortafolioMALH2.Controllers

{
    public class DesarrolladorController : Controller
    {
        desarrolladorDatos _desarrolladorDatos = new desarrolladorDatos();

        public IActionResult Listar()
        {
            //Monstrará una lista de todos los datos del desarrollador
            var oLista = _desarrolladorDatos.Listar();
            return View(oLista);
        }

        public IActionResult Guardar() 
        { 
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(DesarrolladorModel oDesarrolladorModel)
        {
            if(!ModelState.IsValid)
                return View();

            var respuesta = _desarrolladorDatos.Guardar(oDesarrolladorModel);
            if(respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }
}

PortafolioMALH2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PortafolioMALH2.Models;
using System.Diagnostics;

namespace PortafolioMALH2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PortafolioMALH2/Controllers/ProyectoTecsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PortafolioMALH2.Datos;
using PortafolioMALH2.Models;

namespace PortafolioMALH2.Controllers
{
    public class ProyectoTecsController : Controller
    {
        ProyectoTecsDatos _proyectoTecsDatos = new ProyectoTecsDatos();
        //    public IActionResult Listar(string nombreProyecto)
        //    {
        //        var nombresProyectos = _proyectoTecsDatos.ListarProyectos(); // Obtén los nombres de los proyectos
        //        ViewBag.NombresProyectos = nombresProyectos; // Configura ViewBag.NombresProyectos

        //        List<ProyectoTecs> oLista;

        //        if (string.IsNullOrEmpty(nombreProyecto))
        //        {
        //            oLista = _proyectoTecsDatos.Listar(); // Obtén todos los proyectos si nombreProyecto es null o vacío
        //        }
        //        else
        //        {
        //            oLista = _proyectoTecsDatos.ListarPorProyecto(nombreProyecto); // Obtén los proyectos específicos si nombreProyecto tiene un valor
        //        }

        //        return View(oLista);
        //    }

        //}
        [HttpGet]
        [HttpPost]
        public IActionResult Listar(string NombresProyectos)
        {
            var nombresProyectos = _proyectoTecsDatos.ListarProyectos(); // Obtén los nombres de los proyectos
            ViewBag.NombresProyectos = nombresProyectos; // Configura ViewBag.NombresProyectos
            ViewBag.NombreProyectoSeleccionado = NombresProyectos; // Agrega el nombre del proyecto seleccionado a ViewBag

            List<ProyectoTecs> oLista;

            if (string.IsNullOrEmpty(NombresProyectos))
            {
                oLista = _proyectoTecsDatos.Listar(); // Obtén todos los proyectos si nombreProyecto es null o vacío
            }
            else
            {
                oLista = _proyectoTecsDatos.ListarPorProyecto(NombresProyectos); // Obtén los proyectos específicos si nombreProyecto tiene un valor
            }

            return View(oLista);
        }

        //public IActionResult ListarPorProyecto(string nombreProyecto)
        //{
        //    var nombresProyectos = _proyectoTecsDatos.ListarProyectos(); // Obtén los nombres de los proyectos
        //    ViewBag.NombresProyectos = nombresProyectos; // Configura ViewBag.NombresProyectos

        //    List<ProyectoTecs> oLista;

        //    if (string.IsNullOrEmpty(nombreProyecto))
        //    {
        //        oLista = _proyectoTecsDatos.Listar(); // Obtén todos los proyectos si nombreProyecto es null o vacío
        //    }
        //    else
        //    {
        //        oLista = _proyectoTecsDatos.ListarPorProyecto(nombreProyecto); // Obtén los proyectos específicos si nombreProyecto tiene un valor
        //    }

        //    return View(oLista);
        //}


    }
}

PortafolioMALH2/Views/Desarrollador/Guardar.cshtml
@model DesarrolladorModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3>Lista Desarrolladores</h3>
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Desarrollador" method="post">
            <div class="mb-3">
                <label class="form-label">Nombre Completo</label>
                <input asp-for="NombreCompleto" type="text" class="form-control" required/>
            </div>
            <div class="mb-3">
                <label class="form-label">Fecha de Nacimiento</label>
                <input asp-for="FechaNacimineto" type="date" class="form-control" required />
            </div>
            <div class="mb-3">
                <label class="form-label">Número Celular</label>
                <input asp-for="NumCel" type="text" class="form-control" required />
                <span asp-validation-for="NumCel" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Email</label>
                <input asp-for="CorreoElec" type="email" class="form-control" required />
            </div>
            <div class="mb-3">
                <label class="form-label">URL de la imagen</label>
                <input asp-for="ImagenURL" type="text" class="form-control" required />
            </div>
            <div class="mb-3">
                <label class="form-label">Descripción personal</label>
                <textarea asp-for="Descripcion" type="text" class="form-control" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Registrar</button>
            <a asp-action="Listar" asp-controller="Desarrollador" 
            class="btn btn-warning">Volver a Lista</a>
        </form>
        </div>
    </div>

PortafolioMALH2/Views/Desarrollador/Listar.cshtml
@model List<DesarrolladorModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3>Lista Desarrolladores</h3>
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Desarrollador"
           class="btn btn-success">Crear Nuevo +</a>
        <hr />
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre completo</th>
                        <th>Fecha de nacimiento</th>
                        <th>Número celular</th>
                        <th>Correo electrónico</th>
                        <th>Imagen URL</th>
                        <th>Descripción</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.NombreCompleto</td>
                            <td>@item.FechaNacimineto</td>
                            <td>@item.NumCel</td>
                            <td>@item.CorreoElec</td>
                            <td>@item.ImagenURL</td>
                            <td>@item.Descripcion</td>
                            <td>
                                <a asp-action="Editar" asp-controller="DatosPersonales" 
                                class="btn btn-primary btn-sm mb-1" asp-route-IdDatosPersonales="@item.Id">Editar</a>
                                <a asp-action="Eliminar" asp-controller="DatosPersonales" 
                                class="btn btn-danger btn-sm mb-1">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

PortafolioMALH2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="card">
    <div class="card-header">
        <h3>Lista Desarrolladores</h3>
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Desarrollador"
           class="btn btn-success">Crear Nuevo +</a>
        <hr />
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre completo</th>
                        <th>Fecha de nacimiento</th>
                        <th>Número celular</th>
                        <th>Correo electrónico</th>
                        <th>Imagen URL</th>
                        <th>Descripción</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                @* <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.NombreCompleto</td>
                            <td>@item.FechaNacimineto</td>
                            <td>@item.NumCel</td>
                            <td>@item.CorreoElec</td>
                            <td>@item.ImagenURL</td>
                            <td>@item.Descripcion</td>
                            <td>
                                <a asp-action="Editar" asp-controller="DatosPersonales"
                                   class="btn btn-primary btn-sm mb-1" asp-route-IdDatosPersonales="@item.Id">Editar</a>
                                <a asp-action="Eliminar" asp-controller="DatosPersonales"
                                   class="btn btn-danger btn-sm mb-1">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody> *@
            </table>
        </div>
    </div>

</div>

PortafolioMALH2/Views/ProyectoTecs/Listar.cshtml
@model List<ProyectoTecs> 

@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3>Lista de Tecnologías por Proyecto</h3>
    </div>
    <div class="card-body">
        <hr />

        <!-- Envuelve la lista desplegable y la tabla en un formulario -->
        <form method="post" action="Listar">
            <div class="col col-2">
                @Html.DropDownList("NombresProyectos", new SelectList(ViewBag.NombresProyectos, "Value", "Text", ViewBag.NombreProyectoSeleccionado), "Todos los proyectos", new { @class = "form-control custom-dropdown", @onchange = "this.form.submit();" })

            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>

                            <th>Nombre proyecto</th>
                            <th>Descripción</th>
                            <th>Nombre tecnología</th>
                            <th>Versión</th>
                            <th>Porcentaje</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.NombreProyecto</td>
                                <td>@item.descripcion</td>
                                <td>@item.NombreTecnologia</td>
                                <td>@item.Version_tec</td>
                                <td>@item.porcentaje</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </form>
    </div>
</div>

PortafolioMALH2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PortafolioMALH2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PortafolioMALH2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PortafolioMALH2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="menudesplegable"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Desarrollador</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="Desarrollador" 
                                asp-action="Listar">Listar</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Desarrollador"
                                   asp-action="Guardar">Nuevo</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Desarrollador"
                                   asp-action="">Editar</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Desarrollador"
                                   asp-action="">Eliminar</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="menudesplegable"
                               data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tecnología</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="Tecnologia"
                                   asp-action="Listar">Listar</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Tecnologia"
                                   asp-action="Guardar">Nuevo</a>
                                <a class="dropdown-item" asp-area="" asp-controller="#"
                                   asp-action="#">Editar</a>
                                <a class="dropdown-item" asp-area="" asp-controller="#"
                                   asp-action="#">Eliminar</a>
                                <a class="dropdown-item" asp-area="" asp-controller="ProyectoTecs"
                                   asp-action="Listar">Listar por proyecto</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PortafolioMALH2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>